providers:
  current: 'http_api_provider' 
  http_api_provider:
    api_base_url: 'https://testnet.toncenter.com/api/v2/'
    api_key: '76577d29bdc879791f7470c117c3aac144d0b41583dd81fbe4e831740313bce5'
    wait_sec: 1
    wait_max_iters: 10
core:
  fift_path: '/opt/ton/crypto/fift'
  fift_executer_path: '/opt/liteclient-build/crypto/fift'
  func_compiler_path: '/opt/liteclient-build/crypto/func'
  out_path: '../build/'
  secret_path: '../../secrets/'
  wallet_address:  'EQAWYHnDf8qmG9mC1CGD1Svf9_9OjWpDgL9EU2fgsTrfH5jG'
compile:
  src_path: '../code'
  src_files:
    - ['stdlib.fc', 'params.fc', 'op-codes.fc', 'nft-item.fc']
    - ['stdlib.fc', 'params.fc', 'op-codes.fc', 'nft-collection.fc']
    - ['stdlib.fc', 'params.fc', 'op-codes.fc', 'nft-marketplace.fc']
    - ['stdlib.fc', 'params.fc', 'op-codes.fc', 'nft-sale.fc']
  tif_path: '../templates'
  tif_files:
    - ['nft-collection-deploy.tif', 'wallet-external-base.tif']
    - ['nft-item-mint.tif', 'wallet-external-base.tif']
